### PR TITLE
Update to version 1.5.1.

### PR DESCRIPTION
**Pull request by moorepants**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Comment by moorepants** [comment]
@conda-forge-admin, please rerender

**Review by urschrei — APPROVED** [review]
Lgtm!

**Comment by moorepants** [comment]
I think the failure is something about the CI service. Not sure what to do about that. Maybe the auto update bot will work again after this manual update.

**Comment by urschrei** [comment]
Hmm those error messages are quite cryptic. I can push a point update to PyPI and see if it works?

**Comment by moorepants** [comment]
https://github.com/conda-forge/conda-forge.github.io/issues/1604

**Comment by moorepants** [comment]
No, it's happening to everyone.

**Comment by urschrei** [comment]
np, will hold off for now.

**Comment by moorepants** [comment]
Also, it doesn't look like you are pushing a source tarball to pypi. Can you push a source tarball?

**Comment by urschrei** [comment]
> Actually it doesn't look like you are pushing a source tarball to pypi. Can you push a source tarball?

Sorry! Done: https://pypi.org/project/pyzotero/#files

**Pull request merged**
